#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control mate
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-mate-settings.install \
    > ./debian/${CODENAME_SAFE}-mate-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-mate-settings.postinst \
    > ./debian/${CODENAME_SAFE}-mate-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-mate-livesettings.install \
    > ./debian/${CODENAME_SAFE}-mate-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-mate-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-mate-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-mate-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-mate-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-mate-livesettings.service \
    > ./debian/${CODENAME_SAFE}-mate-livesettings.service


## templating

[ -d ./etc ] && rm -rf ./etc
[ -d ./usr ] && rm -rf ./usr
cp -a ../template/etc .
cp -a ../template/usr .

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/automount-open.desktop \
    > ./automount-open.desktop

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/usr/share/mate-background-properties/siduction.xml \
    > ./usr/share/mate-background-properties/siduction.xml

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/usr/share/glib-2.0/schemas/installed/org.mate.desktop.background.gschema.override \
    > ./usr/share/glib-2.0/schemas/installed/org.mate.desktop.background.gschema.override

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/usr/share/glib-2.0/schemas/installed/92_org.gnome.desktop.screensaver.wallpaper.gschema.override \
    > ./usr/share/glib-2.0/schemas/installed/92_org.gnome.desktop.screensaver.wallpaper.gschema.override

grub_template mate


exit 0
